# Set environment variables here that are required by all steps
env:
  # For publishing and using the docker image
  SERVICE_NAME: packet-hardware
  QUAY_REPO: quay.io/packet/${SERVICE_NAME}
  IMAGE_TAG: ${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT}

steps:
   - label: ":test: Run Tests"
     key: "test"
     command: "echo TODO: run the tests here"

   - label: ":build: docker build/push"
     skip: true
     key: "build"
     branches: "master"
     depends_on: ["test"]
     commands: |
       echo --- Build Docker Image - packet-hardware
       docker build . -t "$QUAY_REPO:$IMAGE_TAG"
       docker tag "$QUAY_REPO:$IMAGE_TAG" "$QUAY_REPO:latest"
       echo --- Push Docker Image - packet-hardware
       docker push "$QUAY_REPO:$IMAGE_TAG"
       docker push "$QUAY_REPO:latest"
     plugins:
       - ssh://git@github.com/packethost/ssm-buildkite-plugin#v1.0.1:
           parameters:
             DOCKER_LOGIN_PASSWORD: /buildkite/quay/token/v1
       - docker-login#v2.0.1:
           username: packet+cicd
           server: quay.io
