# Set environment variables here that are required by all steps
env:
  # For publishing and using the docker image
  SERVICE_NAME: packet-hardware
  QUAY_REPO: quay.io/packet/${SERVICE_NAME}
  IMAGE_TAG: ${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_COMMIT}

steps:
   - label: ":test: Python Pylama Tests"
     key: "test-pylama"
     commands:
       - pip install pylama
       - echo Running pylama packethardware setup.py
       - pylama packethardware setup.py
       - echo Done
     plugins:
       - docker#v3.8.0:
          image: "python:3.8-alpine"

   - label: ":test: Python Black Tests"
     key: "test-black"
     commands:
       - pip install black
       - echo Running black --check --diff .
       - black --check --diff .
       - echo Done
     plugins:
       - docker#v3.8.0:
          image: "python:3.8-buster"

   - label: ":build: docker build/push"
     key: "build"
     branches: "master"
     depends_on:
       - "test-pylama"
       - "test-black"
     commands: |
       echo --- Build Docker Image - packet-hardware
       docker build . -t "$QUAY_REPO:$IMAGE_TAG"
       docker tag "$QUAY_REPO:$IMAGE_TAG" "$QUAY_REPO:latest"
       echo --- Push Docker Image - packet-hardware
       docker push "$QUAY_REPO:$IMAGE_TAG"
       docker push "$QUAY_REPO:latest"
     plugins:
       - ssh://git@github.com/packethost/ssm-buildkite-plugin#v1.0.1:
           parameters:
             DOCKER_LOGIN_PASSWORD: /buildkite/quay/token/v1
       - docker-login#v2.0.1:
           username: packet+cicd
           server: quay.io
